### ISSUE TITLE
Web Browser version: Front end / ui issue for Users drop down

### ISSUE THREAD

**Issue by yonglid** [zerobase-io/zerobase_app#2]
. The drop down is in a fixed position as the rest of the site scrolls. Unsure if intentional or if we want to take care of that

**Comment by JohnCLo** [comment]
I investigated this a little bit further. The nav bar is horizontal scrolling on mobile, however uses overflow:none to achieve this. This hides the dropdown if position:relative and I made it position:fixed as a quick solution. Will find a way to compromise the two elements
