### ISSUE TITLE
"Device Registration" modal tells users to check something but doesn't link to it

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/zerobase_app#8]
The modal text reads "Please view our Security section for more details" but gives users no link nor any indication of where that is -- and they can't navigate to it while the modal is active. 

Maybe make this a two-part process, or make this on the modal of login screens where you can view a Privacy Policy before making any decision?

**Comment by JohnCLo** [comment]
Will link to privacy policy once the content is provided by legal

**Comment by JohnCLo** [comment]
Resolved in latest master branch and on staging.zerobase.io. Closing this out.
