### ISSUE TITLE
Hanging on "Device Registration"

### ISSUE THREAD

**Issue by twoangstroms** [zerobase-io/zerobase_app#9]
iPhone XR, iOS 13.3.1

Tried both opening the web app via:

1. Taking a photo of a Zerobase QR code
2. Force-quitting mobile Safari and just opening the web site

![IMG_5979](https://user-images.githubusercontent.com/62673202/77594440-c1eda600-6eb3-11ea-8033-fc8c1a8aacdb.PNG)

**Comment by JohnCLo** [comment]
@twoangstroms Do you have privacy settings enabled for the browser (no cookies, no localStorage)? Could be a logic issue, where the frontend is expecting localStorage or a connectivity issue (still running on Heroku basic tier for now)

**Comment by twoangstroms** [comment]
@JohnCLo At first I thought it was the default mobile Safari that ships on iOS, but then I remembered I do have content blockers enabled, including 1Blocker (https://apps.apple.com/us/app/id1365531024 -- note that there are over 2000 ratings, which would imply not a small installed base). I also have some others.

And I have "Block Pop-ups" enabled in Settings/Safari (again, this is on iOS). I think that's pretty common.

**Comment by JohnCLo** [comment]
This it the wrong repo for these issues - please go to smart tracing from now on. I will make a duplicate issue there for you.

**Comment by twoangstroms** [comment]
Thanks and sorry. I’m new to github and not clear on the distinctions between all the repos, which seemed to be named all the same to me.

> On Apr 3, 2020, at 7:14 AM, John Lo <notifications@github.com> wrote:
> 
> 
> This it the wrong repo for these issues - please go to smart tracing from now on. I will make a duplicate issue there for you.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

dan turner
MIMS 2011
School of Information at UC Berkeley
415.606.4811
www.twoangstroms.com
@ddt
